In [14]:
import pandas as pd

In [15]:
businesses = pd.read_json('data/yelp_academic_dataset_business.json', lines=True)

In [16]:
# create function for filtering by state

def state_filter(dataframe, column, state):
    businesses_new = dataframe[dataframe[column] == state].copy()
    return businesses_new

In [17]:
#filter for all businesses in Pennsylvania 

businesses_pa = state_filter(businesses, 'state', 'PA')

In [18]:
# delete the columns 'address', 'city', 'state', 'postal_code', 'is_open'

businesses_pa.drop(columns=['address', 'city', 'state', 'postal_code', 'is_open'], inplace=True, errors='ignore')

In [19]:
# drop row that have no category labels

businesses_pa.dropna(subset='categories', inplace=True)

In [20]:
# reset index

businesses_pa.reset_index(drop=True, inplace=True)

In [21]:
# import category labels from csv and filter dataframe to keep row that have category label


cat_data = pd.read_csv('data/categories.csv', header=None)

categories = cat_data[0].tolist()

businesses_pa_df = pd.DataFrame()

for index, item in businesses_pa['categories'].items():

    for category in categories:
        if category in item:
            businesses_pa_df = pd.concat([businesses_pa_df, businesses_pa[index:index+1]])
            break

In [22]:
businesses_pa_df

,business_id,name,latitude,longitude,stars,review_count,attributes,categories,hours
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,39.955505,-75.155564,4.0,80,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
1,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,40.338183,-75.471659,4.5,13,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
2,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,39.953949,-75.143226,4.0,245,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-..."
3,ROeacJQwBeh05Rqg7F6TCg,BAP,39.943223,-75.162568,4.5,205,"{'NoiseLevel': 'u'quiet'', 'GoodForMeal': '{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20..."
5,QdN72BWoyFypdGJhhI5r7g,Bar One,39.939825,-75.157447,4.0,65,"{'Smoking': 'u'no'', 'NoiseLevel': 'u'average'...","Cocktail Bars, Bars, Italian, Nightlife, Resta...","{'Monday': '16:0-0:0', 'Tuesday': '16:0-0:0', ..."
...,...,...,...,...,...,...,...,...,...
34002,gPr1io7ks0Eo3FDsnDTYfg,Tata Cafe,40.060414,-75.191084,4.0,21,"{'RestaurantsGoodForGroups': 'True', 'Business...","Sandwiches, Restaurants, Italian","{'Monday': '7:0-17:0', 'Tuesday': '7:0-17:0', ..."
34003,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,40.032483,-75.214430,3.0,55,"{'NoiseLevel': 'u'average'', 'RestaurantsTakeO...","Restaurants, Specialty Food, Food, Sandwiches,...","{'Monday': '10:0-21:0', 'Tuesday': '10:0-21:0'..."
34006,8n93L-ilMAsvwUatarykSg,Kitchen Gia,39.951018,-75.198240,3.0,22,"{'RestaurantsGoodForGroups': 'True', 'BikePark...","Coffee & Tea, Food, Sandwiches, American (Trad...","{'Monday': '9:0-19:30', 'Tuesday': '9:0-19:30'..."
34008,l9eLGG9ZKpLJzboZq-9LRQ,Wawa,39.925656,-75.310344,3.0,11,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Restaurants, Sandwiches, Convenience Stores, C...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
34012,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,39.935982,-75.158665,4.5,35,"{'WheelchairAccessible': 'False', 'Restaurants...","Restaurants, Mexican","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."